### ISSUE TITLE
Crash when using `AEAudioFilePlayerModule`

### ISSUE THREAD

**Issue by Augustyniak** [TheAmazingAudioEngine/TAAE2#12]
Hey,

I get a crash when I use `AEAudioFilePlayerModule` to play audio stored in a file. 

Steps to reproduce:
1. Start playing content of the audio file using `AEAudioFilePlayerModule` class.
2. Set all references to the instance of the `AEAudioFilePlayerModule` class to `nil` in the completion block of the aforementioned class. In most cases there application keeps only one instance to that object.

Block of the renderer looks in the following way:

``` Objective-C
__weak typeof(self) weakSelf = self;
_renderer.block = ^(const AERenderContext * _Nonnull context) {
     __strong typeof(weakSelf) self = weakSelf;
    AEModuleProcess(self.audioFilePlayerModule, context);
    AERenderContextOutput(context, 1);
}
```

Result:
1. Application crashes.

Expected result:
1. No crash. 😀

![crashscreenshot](https://cloud.githubusercontent.com/assets/4410346/15864249/a2741a0c-2cd6-11e6-952b-54dfdb2c2128.jpg)

**Comment by michaeltyson** [comment]
Hi!

Ah, a few problems with your code: if you're going to be setting the reference to nil and you're not taking any other concurrency precautions, you need to use AEManagedValue to maintain a reference to your player. Otherwise, frequently you'll see crashes due to accesses to the invalidated memory from the render thread when you call AEModuleProcess. Check out the way the sample app manages transitory elements, like the recording player:

`
        __unsafe_unretained AEAudioFilePlayerModule * player
         = (__bridge AEAudioFilePlayerModule *)AEManagedValueGetValue(playerValue);
`

Also, I see you're doing an Objective-C property access from the render block - this is a no-no, and will cause glitches in your app. You want to only ever use C on the audio thread.

**Comment by michaeltyson** [comment]
Oh! I think it may also have been a legitimate my-fault crash, as well - I just saw something similar in AEMainThreadEndpoint. I've just committed a fix, so grab the latest version.

**Comment by Augustyniak** [comment]
Thanks for the fast response and fix!

Out of curiosity - Why I shouldn't use Objective-C properties or methods from within the renderer's block? Is this only due to the additional performance hit of Objective-C runtime or are there any additional reasons?

**Comment by michaeltyson** [comment]
This is a good article about the issue: http://www.rossbencina.com/code/real-time-audio-programming-101-time-waits-for-nothing

I'm actually going to write about this myself soon, as I'm seeing lots of devs make this mistake particularly with TAAE2 - I think I may need to find a new architecture that makes it harder to make those mistakes.
