### ISSUE TITLE
Sample code - threading issues accessing balanceSweepRate 

### ISSUE THREAD

**Issue by jackpal** [TheAmazingAudioEngine/TAAE2#36]
AEAudioController has an ivar _balanceSweepRate that's written by the main thread and read by the audio thread.

As far as I can tell, there is currently no guarantee that changes made to _balanceSweepRate by the main thread will be visible to the real-time audio thread. I think it is theoretically possible on a multi-core system for changes to _balanceSweepRate to stay in one core's data cache, and never become visible to the other core.

I'm not how to fix this. Maybe add "volatile" and use a memory barrier when writing it.

**Comment by michaeltyson** [comment]
As I understand it, ARM processors starting with the Cortex-A9 series (e.g. iPad 2 and up) provide hardware cache coherency (the Cortex-A9 had a '[Snoop Control Unit](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0407e/CDDEHDDG.html)'); the more recent chips like the ARMv8-A (Apple A9) in the iPhone 6s Plus use a '[Cache Coherent Interconnect](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.den0024a/BABGJHAB.html)'. So we're fine as far as cache coherency goes.

As far as compiler optimization correctness goes, 'volatile' is indeed useful for [ensuring that a variable is loaded from memory each time](https://developer.arm.com/docs/dui0472/l/compiler-coding-practices/compiler-optimization-and-the-volatile-keyword), rather than being optimised into a local register. In the case you describe, though, it's not important if _balanceSweepRate is read once and cached, or read from memory each time, because we only use it once in the function, and we're not doing anything tricky like looping around the variable access. So it gets read from memory when it's first used in the function, of course, and after that we don't care if the value is just local.

Using volatile and memory barriers comes at a cost, and it's best to use them only when necessary, especially when working with the realtime thread.

Further reading: https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Multithreading/ThreadSafety/ThreadSafety.html

**Comment by michaeltyson** [comment]
...Good attention to detail, though! Please keep it up, and if you see anywhere else that looks like it's missing important synchronization primitives, lemme know.
