### ISSUE TITLE
An update on TAAE2 

### ISSUE THREAD

**Issue by davidbehrend** [TheAmazingAudioEngine/TAAE2#48]
Hi MIchael,
would you mind giving a quick update on the current state of TAAE2?

I'm guessing you're busy getting AB3 out the door, but as TAAE2 has been in beta for nearly 8 months, and as updates have been a little slow lately I'd love a quick confirmation that I'm betting on the right framework.

If you wouldn't mind:

1) Is TAAE2 the preferred choice over TAAE1 at this point?
2) Can we expect v1.0 in the not too distant future?

Thanks again for all your hard work.

**Comment by michaeltyson** [comment]
Hey @toydivision,

I'll be making an announcement about this soon (just waiting for AudioKit to get official Audiobus support before I pull the trigger), but I've decided to actually retire both TAAE and TAAE2 officially, due to my total inability to cope with the number of incoming requests for help. It's become clear that I'm just not able to keep up with support requests from devs, what with my Loopy 3 responsibilities plus imminent new fatherhood about to make it worse.

So: AudioKit's my suggested choice - it's vastly superior to TAAE for general usability and, frankly, feature set, and as soon as there are some good associated Audiobus resources (which are nearly there), I'll be making it official.

My own stuff uses TAAE2, and will continue to do to so, so the repo's gonna stay online and continue to get commits, but only stuff that concerns my own products directly - I'm not going to be able to work on other features.

I think this is for the best though; I believe almost everyone should be using AudioKit, or the framework it's built upon, AVAudioEngine.

**Comment by davidbehrend** [comment]
Thanks for the fast reply!

I had a sneaking suspicion that this might be the case...

I must say that I'm a little saddened to hear this, as I've loved working with TAAE and have learnt so much from reading your immaculate code but it sounds like it's the right decision to make.
